name: Test Project
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # These do not run in the repo, just on a machine with github. So we need get it onto the runner
      # Actions: complex repeated task. 
      # https://github.com/marketplace
      # https://github.com/actions/checkout
      - name: Get code
        uses: actions/checkout@v3 

      # npm is already installed per:
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
      # Though we will do an upgrade here for version 18
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Run test
        run: npm test

